[package]
name = "pallas-crypto"
description = "Cryptographic primitives for Cardano"
version = "1.0.0-alpha.2"
edition = "2021"
repository = "https://github.com/txpipe/pallas"
homepage = "https://github.com/txpipe/pallas"
documentation = "https://docs.rs/pallas-crypto"
license = "Apache-2.0"
readme = "README.md"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Andrew Westberg <andrewwestberg@gmail.com>"]

[dependencies]
hex = "0.4"
cryptoxide = { version = "0.4.4" }
thiserror = "1.0"
rand = "0.9"
rand_chacha = "0.9"
rand_core = "0.9"
pallas-codec = { version = "=1.0.0-alpha.2", path = "../pallas-codec" }
serde = { version = "1.0.143", features = ["derive"]}
serde_with = "3.11.0"
blake2 = "0.10.6"
ed25519-dalek = { version = "2" }

[dev-dependencies]
itertools = "0.13"
quickcheck = "1.0"
quickcheck_macros = "1.0"
serde_test = "1.0.143"

[features]
default = []
